Sort a given sequence numbers
giangle-unikie/complex-copy-cpp pull request #8
Opened 2023-02-13 12:33 UTC by giangle-unikie

The program will sort given numbers, if there is any value that is not a number in the list, the program will print an error message and exit.

2023-02-13 13:08 UTC, millavalio-Unikie requested changes
A few comments. I did not actually test my code suggestion so apologies if there are some syntax errors in them.

2023-02-13 13:08 UTC, milva-unikie commented on python/sort_number.py
> +        check_value_int = isinstance(value, int)
'isinstance()' can be given multiple types, so I don't think there is need to check them separately in this case.

`isinstance(value, (int, float))` should work just the same.

2023-02-13 13:08 UTC, milva-unikie commented on python/sort_number.py
> +            print("Error: " + str(value) + " is not integer or float.")
I would prefer using comma in prints. With comma there is no need to do type changes or add additional spaces before and after the variable
```suggestion
            print("Error:", value, "is not integer or float.")
```

2023-02-13 13:08 UTC, millavalio-Unikie commented on python/sort_number.py
> +    numbers = [3.9, 1.16, 4, 111, 5, 9, 2, 6, 5, 3, 5.0001]
Testing the program would be easier it there would be a option to input the list either as an argument to the program or as an input asked in main (even though the assignment does not specify this clearly).

2023-02-13 13:08 UTC, millavalio-Unikie commented on python/sort_number.py
> +#This function will sort a given sequence of numbers
It is recommended in the Python guidelines that between the imports and every function, there is two empty lines.

2023-02-13 15:02 UTC, milva-unikie requested changes
This new version can not handle negative numbers

> Enter the numbers separated by space: -2
> Error:  -2  is not integer or float.

2023-02-13 15:02 UTC, milva-unikie commented on python/sort_number.py
> +        check_value_number = value.replace('.', '', 1).isdigit()
'check_value_number' is pretty unclear variable name, I think for example 'value_is_number' would make more sense.

2023-02-13 15:02 UTC, milva-unikie commented on python/sort_number.py
> +            print("Error: " ,value, " is not integer or float.")
As I mentioned in my last comments, no need for the spaces inside the quotes before and after the variable if using commas. Python adds the spaces automatically.
```suggestion
            print("Error:", value, "is not integer or float.")
```

2023-02-13 15:06 UTC, giangle-unikie commented on python/sort_number.py
> +        check_value_number = value.replace('.', '', 1).isdigit()
Ok, I will change it.

2023-02-14 06:45 UTC, jounraun commented
$ python3 sort_number.py 
Enter the numbers separated by space: 8 6 22 888 -1 2222
['-1', '22', '2222', '6', '8', '888']

2023-02-14 13:43 UTC, closed without merging

2023-02-15 08:10 UTC, jourau commented
ok